### ISSUE TITLE
Rails PR

### ISSUE THREAD

**Issue by coder2000** [podqueue/rails-hidden_autocomplete#2]
The gem is a great fix for now but if it hasn't already you should open this as a PR for rails as well.

**Comment by ryanfb** [comment]
Thanks, I wasn't sure how well received it would be or how long it would take to get into a release, so I figured a gem was a good first step. I'll see if I can reroll these changes into a PR for Rails, though it may need to be guarded by a new framework default configuration value for ActionView as well.

**Comment by ryanfb** [comment]
Well, this is now merged into Rails! 🎉

This gem should still be useful for Rails 6.1.x users, and possibly others with work on #1.
